language: node_js
node_js:
  - "10"
  - "8"
notifications:
  recipients:
    - piro.outsider.reflex@gmail.com
before_script:
  - npm install
  - make update_extlib
  - make install_extlib
script:
  - make lint
deploy:
  provider: releases
  api_key:
    secure: "NyIOePebjitERgnSO5nwiC4kraHJK8lqClyhrWxeNVDuDseu3Lwg7Ja++UyxEh08496uyhylErFBUJf6ikoopqZYvEUhjsVbLYUI0ejr9G0TLVu3Zb1IV4s+J2w+QIW3d7DOCIskVmuRAZjlTVuiHJZCw9wHm3ot6vyT5e9SofuQtnfsZECsAG5L7+/HWdg61dVlx1n/bUrzInvHzzgcMBTZWJi8meub1TqhvQZ1U1EOM+COhDdsGYdOSO/5EpOIVMQJ227wLVszggHxt+CX7Ineyu7jlriwVN7QJfq9Gjqpo11MWY+cycRPJBsyeEvgMM/FsLKkv1N3laWLT37U6GHs7eJjF2PvToMdvcyd66mYRvgoNs2T6JOFmBwqRjO7Wc+7HW8ftHPWh2ZkitvEY+LZuCsRUkrw2BEKha+GFR+o28aHfjoi9h9i+LxQywpjqmEZYCbSromrbGb5YSaMQrvNxWzyCAiNGremnbLXpmkDFV2Np1vDZe3JKanbePehlPEcGz048bBus1a8vyMAl6xYKODR/vz+0p6ijWGG8fwQ5mOhZzj0pDGA33bqvjjEehNniNIkpki6P9JFJWrGiYm/1c6yKkcOcA/jbmJWaJ1NwwwI3Dwm4Rn2pE+bz6owMnTW+oaTfvjyJXuGkDnQWJ17iUElyCMGXV4nv8+HKZ4="
  file:
    - copy-selected-tabs-to-clipboard.xpi
  skip_cleanup: true
  on:
    repo: piroor/copy-selected-tabs-to-clipboard
    tags: true
